export const QUESTIONS_INCREMENT_INDEX = 'QUESTIONS_INCREMENT_INDEX';
export const QUESTIONS_ADD = 'QUESTIONS_INCREMENT_INDEX';
export const QUESTIONS_LOADING = 'QUESTIONS_LOADING';
export const QUESTIONS_LOADED = 'QUESTIONS_LOADED';
export const QUESTIONS_ON_ANSWER = 'QUESTIONS_ON_ANSWER';
export const QUESTIONS_RESET = 'QUESTIONS_RESET';

export const GAME_INCREASE_SCORE = 'GAME_INCREASE_SCORE';
export const GAME_DECREASE_SCORE = 'GAME_DECREASE_SCORE';
export const GAME_RESET = 'GAME_RESET';
export const GAME_SET_DIFFICULTY = 'GAME_SET_DIFFICULTY';
export const GAME_SET_STAGE = 'GAME_SET_STAGE';